### ISSUE TITLE
Docker image OpenAlea Python 2

### ISSUE THREAD

**Issue by pradal** [openalea/docker-stacks#4]
The image run well
However the PATH is not up to date. Failure: 
```bash
aml -i
```

To solve it, update the  PATH
```bashL
export PATH=/usr/lib/python2.7/dist-packages/bin:$PATH
```

**Comment by thomasarsouze** [comment]
Environment should now be set correctly. Corrected, image uploaded and tested with no problem. @pradal please test the new image and close if works correctly on your side.

**Comment by pradal** [comment]
Nope. 
The PATH variable is not set. It does not contains `/usr/lib/python2.7/dist-packages/bin`

**Comment by pradal** [comment]
Solved in the **latest** image.
